Ai photogram industrial 2
aizatibraimova/photogram-industrial pull request #2
Opened 2024-06-28 21:36 UTC by aizatibraimova

2024-06-28 21:41 UTC, aborov approved these changes
awesome work!

2024-07-01 15:46 UTC, thierrychau requested changes
Hi Aizat,

Great job on this first PR. I do not see your migrations for `devise` and `photos`, could you include them in this PR?

Everything else look good otherwise, besides a minor comment (see below)

2024-07-01 15:46 UTC, thierrychau commented on app/models/like.rb
> +  validates :user_id, uniqueness: { scope: :photo_id, message: "has already liked this photo" }
The foreign key is called `fan_id`, so I believe you need to validate on `fan_id` and not `user_id`

2024-07-01 16:03 UTC, thierrychau approved these changes
Good to merge!

2024-07-01 16:04 UTC, merged